config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'posts/index'
  root to: "posts#index"
  resources :posts do
    resources :reviews, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :url,   presence: true, format: { with: /\A#{URI::regexp(%w(http https))}\z/, message: 'を適切に入力してください' }
  validates :image, presence: true
  belongs_to :user
  has_one_attached :image
  has_many :reviews, dependent: :destroy
  has_many :favorites

  def liked_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :total, presence: true
  validates :concept, presence: true
  validates :quality, presence: true
  validates :usability, presence: true
  validates :utility, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 6 }
  has_many :posts
  has_many :reviews
  has_many :favorites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_post 
  before_action :move_to_index 

  def create
    favorite = current_user.favorites.build(post_id: params[:post_id])
    favorite.save
    render 'create.js.erb'
  end

  def destroy
    favorite = Favorite.find_by(post_id: params[:post_id], user_id: current_user.id)
    favorite.destroy
    render 'destroy.js.erb'
  end

  private
  def set_post
    @post = Post.find(params[:post_id])
  end

  def move_to_index
    unless user_signed_in? || @post.user_id != current_user.id
      redirect_to root_path
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user! ,only: [:new, :edit, :destroy]
  before_action :set_post ,only: [:edit, :update, :show]
  before_action :move_to_index, only: [:edit, :update, :destory]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @review = Review.new
    @reviews = @post.reviews.includes(:user)
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post.id)
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :image).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def move_to_index
    unless @post.user_id == current_user.id
      redirect_to action: :index
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    if @review.save
      redirect_to post_path(@review.post)
    else
      @post = @review.post
      @reviews = @post.reviews
      render 'posts/show'
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @review = @post.reviews.find(params[:id])
    if current_user.id == @review.user.id
      @review.destroy
      redirect_to post_path(@review.post)
    else
      render 'posts/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:total, :concept, :quality, :usability, :utility, :text).merge(user_id: current_user.id,
                                                                                                  post_id: params[:post_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    favorites= Favorite.where(user_id: @user.id).pluck(:post_id)
    @favorite_posts = Post.find(favorites)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_favorite.html.erb
<% if user_signed_in? && post.liked_by?(current_user)%>
  <%=link_to "いいね済", post_favorites_path(post.id),  method: :delete, class: "post_favorites", remote: true %>
<% else %>
  <%=link_to "いいねする", post_favorites_path(post.id), method: :post, class: "post_favorites", remote: true %>
<% end %>

app/views/favorites/create.js.erb
document.getElementById("like-btn<%= @post.id %>").innerHTML = "<%= j(render partial: 'favorites/favorite', locals: {post: @post}) %>"

app/views/favorites/destroy.js.erb
document.getElementById("like-btn<%= @post.id %>").innerHTML = "<%= j(render partial: 'favorites/favorite', locals: {post: @post}) %>"

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
 <div class="error-alert">
   <ul>
     <% model.errors.full_messages.each do |message| %>
       <li class='error-message'><%= message %></li>
     <% end %>
   </ul>
 </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>KAKKO</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>

          <% if user_signed_in? %>
             <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
              <%= link_to "New Website", new_post_path, class: :nav__btn %>
             </div>

            <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
            <% end %>
          
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © KAKKO All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: post, local: true do |f|%>
  <div class="field">
    <%= f.label :title, "サイトの名称" %><br />
    <%= f.text_field :title, id:"post_title" %>
  </div>

  <div class="field">
    <%= f.label :url, "URL" %><br />
    <%= f.text_field :url, id:"post_url" %>
  </div>

  <div class="field">
    <%= f.label :image, "サイトの画像" %><br />
    <%= f.file_field :image, id:"post_image" %>
  </div>

  <div class="actions"><br />
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="card">
  <%= link_to image_tag(post.image, class: :card__img ), post_path(post.id)%>
  <div class="card__body">
    <%= link_to post.title, post.url, class: :card__title%>
    <%= link_to "by #{post.user.name}", user_path(post.user_id), class: :card__user %>
  </div>

  <% if user_signed_in? && current_user != post.user %>
  <div id="like-btn<%= post.id %>">
    <%= render partial: "favorites/favorite", locals: { post: post } %>
  </div>
  <% end %>
  
</div>

app/views/posts/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">編集</h2>
      <%= render partial: "form", locals: { post: @post } %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<main class="main">
  <div class="inner">
    
    <% if user_signed_in? %>
      <div class="greeting">
        <%= "こんにちは、" %>
        <%= link_to "#{current_user.name}さん", user_path(current_user.id), class: :greeting__link%>
      </div>
    <% end %>
    
    <div class="card__wrapper">
      <%= render partial: "post", collection: @posts %>
    </div>
  </div>
</main>

app/views/posts/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">サイトを投稿する</h2>
      <%= render 'layouts/error_messages', model: @post %>
      <%= render partial: "form", locals: { post: @post } %>
      
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @post.title%>
      </p>
      <%= link_to "by #{@post.user.name}", user_path(@post.user.id), class: :prototype__user %>
      <% if user_signed_in? && current_user.id == @post.user_id %>
        <div class="prototype__manage">
          <%= link_to "編集する", edit_post_path(@post.id), class: :prototype__btn %>
          <%= link_to "削除する", post_path(@post.id), method: :delete, class: :prototype__btn %>
        </div>
      <% end %>
      <div class="prototype__image">
        <%= image_tag @post.image %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">URL</p>
          <p class="detail__message">
            <%= link_to @post.url, @post.url%>
          </p>
        </div>
        
      </div>
      <div class="prototype__comments">
        <% if user_signed_in? %>
        <%= render 'layouts/error_messages', model: @review %>
          <%= form_with model: [@post, @review],local: true do |f|%>
            <div class="field">
              <%= f.label :total, "総合評価" %><br />
              <%= f.radio_button :total, '5', id:"comment_content" %>
              <%= f.label :total, "5点" %>
              <%= f.radio_button :total, '4', id:"comment_content" %>
              <%= f.label :total, "4点" %>
              <%= f.radio_button :total, '3', id:"comment_content" %>
              <%= f.label :total, "3点" %>
              <%= f.radio_button :total, '2', id:"comment_content" %>
              <%= f.label :total, "2点" %>
              <%= f.radio_button :total, '1', id:"comment_content" %>
              <%= f.label :total, "1点" %>
            </div>
            <div class="field">
              <%= f.label :concept, "世界観" %><br />
              <%= f.radio_button :concept, '5', id:"comment_content" %>
              <%= f.label :concept, "5点" %>
              <%= f.radio_button :concept, '4', id:"comment_content" %>
              <%= f.label :concept, "4点" %>
              <%= f.radio_button :concept, '3', id:"comment_content" %>
              <%= f.label :concept, "3点" %>
              <%= f.radio_button :concept, '2', id:"comment_content" %>
              <%= f.label :concept, "2点" %>
              <%= f.radio_button :concept, '1', id:"comment_content" %>
              <%= f.label :concept, "1点" %>
            </div>
            <div class="field">
              <%= f.label :quality, "見栄え" %><br />
              <%= f.radio_button :quality, '5', id:"comment_content" %>
              <%= f.label :quality, "5点" %>
              <%= f.radio_button :quality, '4', id:"comment_content" %>
              <%= f.label :quality, "4点" %>
              <%= f.radio_button :quality, '3', id:"comment_content" %>
              <%= f.label :quality, "3点" %>
              <%= f.radio_button :quality, '2', id:"comment_content" %>
              <%= f.label :quality, "2点" %>
              <%= f.radio_button :quality, '1', id:"comment_content" %>
              <%= f.label :quality, "1点" %>
            </div>
            <div class="field">
              <%= f.label :usability, "わかりやすさ" %><br />
              <%= f.radio_button :usability, '5', id:"comment_content" %>
              <%= f.label :usability, "5点" %>
              <%= f.radio_button :usability, '4', id:"comment_content" %>
              <%= f.label :usability, "4点" %>
              <%= f.radio_button :usability, '3', id:"comment_content" %>
              <%= f.label :usability, "3点" %>
              <%= f.radio_button :usability, '2', id:"comment_content" %>
              <%= f.label :usability, "2点" %>
              <%= f.radio_button :usability, '1', id:"comment_content" %>
              <%= f.label :usability, "1点" %>
            </div>
            <div class="field">
              <%= f.label :utility, "実用的" %><br />
              <%= f.radio_button :utility, '5', id:"comment_content" %>
              <%= f.label :utility, "5点" %>
              <%= f.radio_button :utility, '4', id:"comment_content" %>
              <%= f.label :utility, "4点" %>
              <%= f.radio_button :utility, '3', id:"comment_content" %>
              <%= f.label :utility, "3点" %>
              <%= f.radio_button :utility, '2', id:"comment_content" %>
              <%= f.label :utility, "2点" %>
              <%= f.radio_button :utility, '1', id:"comment_content" %>
              <%= f.label :utility, "1点" %>
            </div>
            <div class="field">
              <%= f.label :text, "コメント（任意）" %><br />
              <%= f.text_area :text, id:"comment_content" %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %>
        <% end %>

        <% if @reviews.present? %>
          <ul class="comments_lists">
            <h4>＜評価一覧＞</h4>
            <% @reviews.each do |review| %>
              <ul class="comments_list">
                  <strong><%= link_to "（ #{review.user.name} ）", user_path(review.user.id), class: :comment_user %>
                <%= "総合評価 : #{review.total}点" %></strong><br />
                <%= "世界観 : #{review.concept}点" %>
                <%= "見栄え : #{review.quality}点" %>
                <%= "わかりやすさ : #{review.usability}点" %>
                <%= "実用的 : #{review.utility}点" %><br />

                <% unless review.text == "" %>
                  <%= "コメント : #{review.text}" %>
                <% end %>

                <% if user_signed_in? && current_user.id == review.user_id %>
                  <div class="review__manage">
                    <%= link_to "レビューを削除する", post_review_path(@post, review), method: :delete, class: :review__btn %>
                  </div>
                <% end %>
              </ul>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <% if @posts.present? %>
        <h2 class="page-heading">
          <%= "#{@user.name}さんの投稿したサイト"%>
        </h2>
        <div class="user__card">
          <%= render partial: "posts/post", collection: @posts %>
        </div>
      <% else %>
        <h3>サイトがまだ投稿されていません</h3>
      <% end %>

      <% if @favorite_posts.present? %>
        <h2 class="page-heading">
          <%= "#{@user.name}さんのお気に入りしたサイト"%>
        </h2>
        
        <div class="user__card">
          <%= render partial: "posts/post", collection: @favorite_posts %>
        </div>
      <% else %>
        <h3>まだお気に入り登録をしていません</h3>
      <% end %>
    </div>
  </div>
</div>